# Generated by Django 4.2.11 on 2024-04-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('logging', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
