# Generated by Django 4.2.11 on 2024-04-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descriptor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
